import test from 'node:test';
import assert from 'node:assert/strict';
import { createAuthService } from '../src/application/auth-service.mjs';
import { createMemoryAuthStore } from '../src/infrastructure/memory-auth-store.mjs';

function fixture(){ let tick=0,id=0; const store=createMemoryAuthStore(); const auth=createAuthService({store,clock:()=>`2026-07-31T10:00:${String(tick++).padStart(2,'0')}.000Z`,nextId:()=>`id-${++id}`,randomBytesImpl:(n)=>Buffer.alloc(n,id),sessionTtlMs:60_000}); return {auth,store}; }
test('bootstrap, login, authenticate and logout', async()=>{ const {auth}=fixture(); const u=await auth.bootstrapUser({id:'user-1',email:'Owner@Syntha.test',password:'correct horse battery staple',displayName:'Owner'}); assert.equal(u.email,'Owner@Syntha.test'); const login=await auth.login({email:'owner@syntha.test',password:'correct horse battery staple'}); assert.match(login.accessToken,/^swv2_/); assert.equal((await auth.authenticate(login.accessToken)).actorId,'user-1'); assert.equal(await auth.logout(login.accessToken),true); assert.equal(await auth.authenticate(login.accessToken),null); });
test('invalid credentials and duplicate users are rejected', async()=>{ const {auth}=fixture(); await auth.bootstrapUser({id:'user-1',email:'owner@syntha.test',password:'correct horse battery staple'}); await assert.rejects(()=>auth.bootstrapUser({id:'user-2',email:'OWNER@syntha.test',password:'another secure password'}),e=>e.code==='AUTH_USER_ALREADY_EXISTS'); await assert.rejects(()=>auth.login({email:'owner@syntha.test',password:'wrong password!!'}),e=>e.code==='AUTH_CREDENTIALS_INVALID'); });
test('expired sessions are not accepted', async()=>{ let now='2026-07-31T10:00:00.000Z'; const auth=createAuthService({store:createMemoryAuthStore(),clock:()=>now,nextId:(()=>{let n=0;return()=>`id-${++n}`})(),randomBytesImpl:(n)=>Buffer.alloc(n,3),sessionTtlMs:60_000}); await auth.bootstrapUser({id:'u',email:'u@syntha.test',password:'correct horse battery staple'}); const login=await auth.login({email:'u@syntha.test',password:'correct horse battery staple'}); now='2026-07-31T10:02:00.000Z'; assert.equal(await auth.authenticate(login.accessToken),null); });

// Личность, заведённая отключённой: идентификатор занят, войти под ним нельзя. Нужна там, где
// членство обязано называть существующего человека, а входить этому человеку незачем.
test('a disabled identity exists and cannot sign in', async()=>{ const {auth}=fixture(); await auth.bootstrapUser({id:'actor-1',email:'actor@syntha.test',password:'correct horse battery staple',status:'disabled'}); await assert.rejects(()=>auth.login({email:'actor@syntha.test',password:'correct horse battery staple'}),e=>e.code==='AUTH_CREDENTIALS_INVALID'); });
test('an identity status other than active or disabled is refused', async()=>{ const {auth}=fixture(); await assert.rejects(()=>auth.bootstrapUser({id:'actor-2',email:'actor2@syntha.test',password:'correct horse battery staple',status:'suspended'}),e=>e.code==='AUTH_USER_STATUS_INVALID'); });
test('an identity is active unless it is asked to be otherwise', async()=>{ const {auth}=fixture(); await auth.bootstrapUser({id:'actor-3',email:'actor3@syntha.test',password:'correct horse battery staple'}); const login=await auth.login({email:'actor3@syntha.test',password:'correct horse battery staple'}); assert.equal((await auth.authenticate(login.accessToken)).actorId,'actor-3'); });
