import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
const source=(path)=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const roles=['table','filterbar','card','status','inspector','button','field'];

test('the final runtime exposes Omnidata Design System v1 through seven canonical roles',async()=>{const js=await source('public/modules/omnidata-v14-role-system.js');assert.doesNotThrow(()=>new Function(js));for(const token of ["const BUILD='visual-20260806-14-role-system-1'","const DESIGN_SYSTEM='omnidata-design-system-v1'","const VERSION='1.0.0'","const CORE_ROLES=Object.freeze(['table','filterbar','card','status','inspector','button','field'])",'COMPONENT_TO_ROLE','COMPONENT_PART','EXPLICIT_SELECTORS','EXACT_PARTS','CLASS_RULES','dataset.odsRole','dataset.odsPart','data-od14-unified-role','STRICT_PAIRS','RU_ALIASES','EN_ALIASES','translateAliases','translateInterface','decorateAbbreviations','auditMixedLanguage','auditLanguage','odsLanguageAudit','odsName','odsVersion','MutationObserver','syntha:locale-changed','SynthaOmnidataDesignSystemV1','SynthaOmnidataV14RoleSystem'])assert.ok(js.includes(token),token);for(const role of roles)assert.ok(js.includes(`${role}:`)||js.includes(`'${role}'`),role)});

test('the final CSS is token-driven, role-driven and contains no module-specific visual fork',async()=>{const css=await source('public/omnidata-v14-role-system.css');for(const role of roles){assert.ok(css.includes(`[data-ods-role="${role}"]`),`ods:${role}`);assert.ok(css.includes(`[data-od14-unified-role="${role}"]`),`compat:${role}`)}for(const token of ['--ods-font-family:Arial,"Helvetica Neue",Helvetica,sans-serif','--ods-color-workspace:#f2f4f5','--ods-color-sidebar:#303640','--ods-color-accent:#ff5b22','--ods-space-1:4px','--ods-space-6:32px','--ods-control-height:34px','--ods-row-height:42px','--ods-radius-md:5px','--ods-content-max:1760px','--ods-inspector-width:360px','--odr-bg:var(--ods-color-workspace)','--odr-sidebar:var(--ods-color-sidebar)','--odr-accent:var(--ods-color-accent)','--odr-control-height:var(--ods-control-height)','--odr-row-height:var(--ods-row-height)','--odr-radius:var(--ods-radius-md)','border-collapse:separate!important','font-variant-numeric:tabular-nums!important','prefers-reduced-motion'])assert.ok(css.includes(token),token);assert.doesNotMatch(css,/@import|https?:\/\//i);assert.doesNotMatch(css,/\.(?:tech-pack|production-orders|production-execution|final-quality|measurement-|sample-|sourcing-|bom-|ls9-)/i);assert.doesNotMatch(css,/:has\(/)});

test('ODS v1 is declared in the shell and remains the final visual/runtime layer',async()=>{const html=await source('public/index.html');const handler=await source('src/web/static-handler.mjs');assert.match(html,/<meta name="syntha-design-system" content="omnidata-design-system-v1">/);assert.match(html,/<meta name="syntha-design-system-version" content="1\.0\.0">/);const style=['/final-quality.css?v=industrial-20260805-1','/omnidata-v14-extensions.css?v=visual-20260805-14-components-4','/omnidata-v14-role-system.css?v=visual-20260806-14-role-system-1'];let previous=-1;for(const asset of style){const index=html.indexOf(asset);assert.ok(index>previous,asset);previous=index}const scripts=['/ui/final-quality.js?v=industrial-20260805-1','/ui/omnidata-v14-components.js?v=visual-20260805-14-components-4','/ui/omnidata-v14-role-system.js?v=visual-20260806-14-role-system-1','/ui/dom-boolean-props.js?v=visual-20260804-9','/ui/app-start.js?v=visual-20260805-14-components-4'];previous=-1;for(const asset of scripts){const index=html.indexOf(asset);assert.ok(index>previous,asset);previous=index}for(const mapping of ["'/omnidata-v14-role-system.css': ['omnidata-v14-role-system.css', 'text/css; charset=utf-8', VISUAL_CACHE]","'/ui/omnidata-v14-role-system.js': ['modules/omnidata-v14-role-system.js', JS, VISUAL_CACHE]","'/final-quality.css': ['final-quality.css', 'text/css; charset=utf-8', VISUAL_CACHE]","'/ui/final-quality-core.js': ['modules/final-quality-core.js', JS, VISUAL_CACHE]","'/ui/final-quality.js': ['modules/final-quality.js', JS, VISUAL_CACHE]"])assert.ok(handler.includes(mapping),mapping)});
