import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createServer } from 'node:http';
import path from 'node:path';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { createStandaloneHandler } from '../src/web/static-handler.mjs';
const publicDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','public');
async function withServer(handler,work){const server=createServer(handler);server.listen(0,'127.0.0.1');await once(server,'listening');try{await work(`http://127.0.0.1:${server.address().port}`)}finally{server.close();await once(server,'close')}}

test('the shell loads every implemented workspace beneath Omnidata Design System v1',async()=>{const html=await readFile(path.join(publicDir,'index.html'),'utf8');assert.match(html,/meta name="syntha-design-system" content="omnidata-design-system-v1"/);for(const asset of ['omnidata-v14.css?v=visual-20260805-14','omnidata-v14-module-adapters.css?v=visual-20260805-14-module-adapters-1','omnidata-v14-extensions.css?v=visual-20260805-14-components-4','omnidata-v14-role-system.css?v=visual-20260806-14-role-system-1','tech-packs.js?v=industrial-20260805-3','production-orders.js?v=industrial-20260805-1','production-executions.js?v=industrial-20260805-1','final-quality.js?v=industrial-20260805-1'])assert.ok(html.includes(asset),asset);for(const retired of ['tech-packs.css','production-executions.css','production-orders.css','final-quality.css'])assert.ok(!html.includes(retired),retired);const styles=[...html.matchAll(/<link\s+[^>]*rel="stylesheet"[^>]*href="([^"]+)"/g)].map(m=>new URL(m[1],'http://syntha.local').pathname);assert.equal(styles.at(-1),'/omnidata-v14-role-system.css');const scripts=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(m=>new URL(m[1],'http://syntha.local').pathname);assert.ok(scripts.indexOf('/ui/tech-packs.js')<scripts.indexOf('/ui/production-orders.js'));assert.ok(scripts.indexOf('/ui/production-orders.js')<scripts.indexOf('/ui/production-executions.js'));assert.ok(scripts.indexOf('/ui/production-executions.js')<scripts.indexOf('/ui/final-quality.js'));assert.equal(scripts.at(-1),'/ui/app-start.js')});

test('the standalone server delivers ODS-native runtimes and rejects retired workspace stylesheets',async()=>{const handler=createStandaloneHandler({publicDir,apiHandler:(_request,response)=>{response.statusCode=404;response.end()}});await withServer(handler,async(base)=>{for(const asset of ['/ui/tech-packs.js','/ui/production-orders.js','/ui/production-executions.js','/ui/final-quality.js','/omnidata-v14-module-adapters.css','/omnidata-v14-role-system.css']){const response=await fetch(`${base}${asset}`);assert.equal(response.status,200,asset);assert.equal(response.headers.get('cache-control'),'no-store',asset)}for(const retiredAsset of ['/tech-packs.css','/production-executions.css','/production-orders.css','/final-quality.css']){const retired=await fetch(`${base}${retiredAsset}`);assert.equal(retired.status,404,retiredAsset)}})});
