import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createServer } from 'node:http';
import path from 'node:path';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import { createStandaloneHandler } from '../src/web/static-handler.mjs';
const publicDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','public');
async function withServer(handler,work){const server=createServer(handler);server.listen(0,'127.0.0.1');await once(server,'listening');try{await work(`http://127.0.0.1:${server.address().port}`)}finally{server.close();await once(server,'close')}}

test('the shell loads every implemented workspace beneath Omnidata Design System v1',async()=>{const html=await readFile(path.join(publicDir,'index.html'),'utf8');assert.match(html,/meta name="syntha-build" content="visual-20260805-14"/);assert.match(html,/meta name="syntha-design-system" content="omnidata-design-system-v1"/);assert.match(html,/meta name="syntha-design-system-version" content="1\.0\.0"/);for(const asset of ['tech-packs.css?v=industrial-20260805-3','production-executions.css?v=industrial-20260805-1','omnidata-v14.css?v=visual-20260805-14','omnidata-v14-module-adapters.css?v=visual-20260805-14-module-adapters-1','omnidata-v14-extensions.css?v=visual-20260805-14-components-4','omnidata-v14-role-system.css?v=visual-20260806-14-role-system-1','tech-packs.js?v=industrial-20260805-3','production-orders.js?v=industrial-20260805-1','production-executions.js?v=industrial-20260805-1','final-quality-core.js?v=industrial-20260805-1','final-quality.js?v=industrial-20260805-1','omnidata-v14.js?v=visual-20260805-14','omnidata-v14-module-adapters.js?v=visual-20260805-14-module-adapters-4','omnidata-v14-components.js?v=visual-20260805-14-components-4','omnidata-v14-role-system.js?v=visual-20260806-14-role-system-1'])assert.ok(html.includes(asset),asset);assert.ok(!html.includes('production-orders.css'),'Production Orders must not load a local stylesheet');assert.ok(!html.includes('final-quality.css'),'Final Quality must not load a local stylesheet');const styles=[...html.matchAll(/<link\s+[^>]*rel="stylesheet"[^>]*href="([^"]+)"/g)].map(match=>new URL(match[1],'http://syntha.local').pathname);assert.deepEqual(styles.slice(-11),['/omnidata-v8.css','/omnidata-v8-reference.css','/omnidata-v9.css','/omnidata-v10.css','/omnidata-v11.css','/omnidata-v12.css','/omnidata-v13.css','/omnidata-v14.css','/omnidata-v14-module-adapters.css','/omnidata-v14-extensions.css','/omnidata-v14-role-system.css']);const scripts=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(match=>new URL(match[1],'http://syntha.local').pathname);assert.deepEqual(scripts.slice(-12),['/ui/omnidata-v8.js','/ui/omnidata-v9.js','/ui/omnidata-v10.js','/ui/omnidata-v11.js','/ui/omnidata-v12.js','/ui/omnidata-v13.js','/ui/omnidata-v14.js','/ui/omnidata-v14-module-adapters.js','/ui/omnidata-v14-components.js','/ui/omnidata-v14-role-system.js','/ui/dom-boolean-props.js','/ui/app-start.js']);assert.ok(scripts.indexOf('/ui/production-orders.js')<scripts.indexOf('/ui/production-executions.js'));assert.ok(scripts.indexOf('/ui/final-quality.js')<scripts.indexOf('/ui/omnidata-v8.js'));assert.ok(scripts.indexOf('/ui/production-executions.js')<scripts.indexOf('/ui/final-quality.js'))});

test('the standalone server prevents stale caching of ODS and implemented workspace runtimes',async()=>{const handler=createStandaloneHandler({publicDir,apiHandler:(_request,response)=>{response.statusCode=404;response.end()}});await withServer(handler,async(base)=>{for(const asset of ['/ui/production-orders.js?v=industrial-20260805-1','/ui/final-quality-core.js?v=industrial-20260805-1','/ui/final-quality.js?v=industrial-20260805-1','/omnidata-v14.css?v=visual-20260805-14','/omnidata-v14-module-adapters.css?v=visual-20260805-14-module-adapters-1','/omnidata-v14-extensions.css?v=visual-20260805-14-components-4','/omnidata-v14-role-system.css?v=visual-20260806-14-role-system-1','/ui/omnidata-v14.js?v=visual-20260805-14','/ui/omnidata-v14-module-adapters.js?v=visual-20260805-14-module-adapters-4','/ui/omnidata-v14-components.js?v=visual-20260805-14-components-4','/ui/omnidata-v14-role-system.js?v=visual-20260806-14-role-system-1']){const response=await fetch(`${base}${asset}`);assert.equal(response.status,200,asset);assert.equal(response.headers.get('cache-control'),'no-store',asset)}for(const retiredAsset of ['/production-orders.css','/final-quality.css']){const retired=await fetch(`${base}${retiredAsset}`);assert.equal(retired.status,404,retiredAsset)}});});
