import { DomainError } from '../core/errors.mjs';

// A DomainError can describe a fault on our side rather than a bad request: a reader that broke its
// contract, a clock or RNG that failed. Reporting those as 4xx blames the caller for a server
// problem. Matched by suffix so a new reader/result/clock code is classified on arrival instead of
// waiting to be enumerated. Codes raised only while services are constructed never reach this
// mapper, so covering them here costs nothing.
const SERVER_FAULT_SUFFIXES = Object.freeze(['_RESULT_INVALID', '_READER_REQUIRED', '_READER_UNAVAILABLE', '_CLOCK_INVALID']);
const SERVER_FAULT_CODES = Object.freeze(['AUTH_RANDOM_SOURCE_INVALID']);

export function isServerFaultCode(code) {
  return SERVER_FAULT_CODES.includes(code) || SERVER_FAULT_SUFFIXES.some((suffix) => code.endsWith(suffix));
}

export function normalizeHttpError(error) {
  if (!(error instanceof DomainError)) return { status: 500, code: 'INTERNAL_ERROR', message: 'Unexpected server error', details: {} };
  const code = error.code; let status = 422;
  if (isServerFaultCode(code)) return { status: 500, code, message: error.message, details: error.details ?? {} };
  if (code === 'HTTP_ROUTE_NOT_FOUND' || code.endsWith('_NOT_FOUND')) status = 404;
  else if (['HTTP_AUTH_REQUIRED', 'HTTP_AUTH_INVALID', 'AUTH_CREDENTIALS_INVALID'].includes(code)) status = 401;
  else if (code === 'AUTH_RATE_LIMITED') status = 429;
  else if (code === 'CAPABILITY_DENIED' || code.includes('MEMBERSHIP_REQUIRED')) status = 403;
  else if (code === 'HTTP_CONTENT_TYPE_UNSUPPORTED') status = 415;
  else if ([
    'HTTP_JSON_INVALID', 'HTTP_JSON_OBJECT_REQUIRED', 'HTTP_CONTENT_LENGTH_INVALID', 'HTTP_IDEMPOTENCY_KEY_REQUIRED', 'HTTP_IDEMPOTENCY_KEY_INVALID',
    'HTTP_IDENTIFIER_MISMATCH', 'HTTP_PATH_PARAMETER_INVALID', 'HTTP_BODY_FIELD_UNKNOWN', 'HTTP_BODY_FIELD_INVALID', 'HTTP_QUERY_DUPLICATE',
    'HTTP_QUERY_FIELD_UNKNOWN', 'HTTP_QUERY_INVALID', 'WORKSPACE_LIMIT_INVALID', 'WORKSPACE_SECTION_INVALID', 'WORKSPACE_PAGE_LIMIT_INVALID',
    'WORKSPACE_CURSOR_INVALID', 'NOTIFICATION_LIMIT_INVALID', 'NOTIFICATION_PAGE_LIMIT_INVALID', 'NOTIFICATION_CURSOR_INVALID',
    'CATALOG_ACTOR_INVALID', 'CATALOG_PAGE_LIMIT_INVALID', 'CATALOG_CURSOR_INVALID', 'CATALOG_SEARCH_INVALID', 'CATALOG_STATUS_FILTER_INVALID',
    'CATALOG_BRAND_FILTER_INVALID', 'CATALOG_COLLECTION_FILTER_INVALID', 'CATALOG_EXPECTED_VERSION_INVALID', 'CATALOG_UPDATE_INVALID',
    'CATALOG_PUBLISH_INVALID', 'MATERIAL_ACTOR_INVALID', 'MATERIAL_PAGE_LIMIT_INVALID', 'MATERIAL_CURSOR_INVALID', 'MATERIAL_SEARCH_INVALID',
    'MATERIAL_STATUS_FILTER_INVALID', 'MATERIAL_TYPE_FILTER_INVALID', 'MATERIAL_BRAND_FILTER_INVALID', 'MATERIAL_CODE_INVALID',
    'MATERIAL_EXPECTED_VERSION_INVALID', 'MATERIAL_UPDATE_INVALID', 'MATERIAL_PUBLISH_INVALID',
    'BOM_ACTOR_INVALID', 'BOM_PAGE_LIMIT_INVALID', 'BOM_CURSOR_INVALID', 'BOM_SEARCH_INVALID', 'BOM_STATUS_FILTER_INVALID',
    'BOM_BRAND_FILTER_INVALID', 'BOM_SKU_INVALID', 'BOM_EXPECTED_VERSION_INVALID', 'BOM_UPDATE_INVALID', 'BOM_PUBLISH_INVALID',
    'MEASUREMENT_ACTOR_INVALID', 'MEASUREMENT_PAGE_LIMIT_INVALID', 'MEASUREMENT_CURSOR_INVALID', 'MEASUREMENT_SEARCH_INVALID',
    'MEASUREMENT_STATUS_FILTER_INVALID', 'MEASUREMENT_UNIT_FILTER_INVALID', 'MEASUREMENT_BRAND_FILTER_INVALID', 'MEASUREMENT_SKU_INVALID',
    'MEASUREMENT_EXPECTED_VERSION_INVALID', 'MEASUREMENT_UPDATE_INVALID', 'MEASUREMENT_PUBLISH_INVALID',
    'SAMPLE_ACTOR_INVALID', 'SAMPLE_PAGE_LIMIT_INVALID', 'SAMPLE_CURSOR_INVALID', 'SAMPLE_SEARCH_INVALID', 'SAMPLE_STATUS_FILTER_INVALID',
    'SAMPLE_TYPE_FILTER_INVALID', 'SAMPLE_BRAND_FILTER_INVALID', 'SAMPLE_SKU_FILTER_INVALID', 'SAMPLE_OVERDUE_FILTER_INVALID',
    'SAMPLE_CODE_INVALID', 'SAMPLE_EXPECTED_VERSION_INVALID', 'SAMPLE_INPUT_INVALID', 'SAMPLE_COMMAND_INVALID', 'SAMPLE_NEXT_ROUND_INVALID',
    'SOURCING_ACTOR_INVALID', 'SOURCING_PAGE_LIMIT_INVALID', 'SOURCING_CURSOR_INVALID', 'SOURCING_SEARCH_INVALID',
    'SOURCING_STATUS_FILTER_INVALID', 'SOURCING_BRAND_FILTER_INVALID', 'SOURCING_OVERDUE_FILTER_INVALID',
    'SUPPLIER_COUNTRY_FILTER_INVALID', 'SUPPLIER_CATEGORY_FILTER_INVALID', 'SUPPLIER_CODE_INVALID', 'SUPPLIER_EXPECTED_VERSION_INVALID',
    'SUPPLIER_INPUT_INVALID', 'SUPPLIER_COMMAND_INVALID', 'RFQ_CODE_INVALID', 'RFQ_EXPECTED_VERSION_INVALID', 'RFQ_INPUT_INVALID',
    'RFQ_COMMAND_INVALID', 'RFQ_SKU_FILTER_INVALID', 'RFQ_SUPPLIER_FILTER_INVALID',
    'ORDER_EXPECTED_VERSION_INVALID', 'AUTH_EMAIL_INVALID', 'AUTH_PASSWORD_INVALID',
  ].includes(code)) status = 400;
  else if (code === 'HTTP_BODY_TOO_LARGE') status = 413;
  else if (code.includes('CONFLICT') || code.includes('ALREADY_EXISTS') || [
    'MATERIAL_NOT_DRAFT', 'BOM_NOT_DRAFT', 'MEASUREMENT_NOT_DRAFT', 'SAMPLE_NOT_DRAFT', 'SAMPLE_NOT_REQUESTED',
    'SAMPLE_NOT_RECEIVABLE', 'SAMPLE_NOT_RECEIVED', 'SAMPLE_NOT_CANCELLABLE', 'SAMPLE_NOT_REJECTED', 'SAMPLE_NEXT_ROUND_EXISTS',
    'SUPPLIER_NOT_EDITABLE', 'SUPPLIER_NOT_QUALIFIABLE', 'SUPPLIER_NOT_QUALIFIED', 'SUPPLIER_NOT_ARCHIVABLE',
    'RFQ_NOT_DRAFT', 'RFQ_NOT_OPEN_FOR_QUOTES', 'RFQ_NOT_AWARDABLE', 'RFQ_NOT_ALLOCATABLE', 'RFQ_NOT_CANCELLABLE',
    'RFQ_RESPONSE_DEADLINE_PASSED', 'RFQ_QUOTE_EXPIRED', 'RFQ_SKU_SNAPSHOT_STALE', 'RFQ_BOM_SNAPSHOT_STALE',
  ].includes(code)) status = 409;
  const retryAfterSeconds = code === 'AUTH_RATE_LIMITED' ? Math.max(1, Math.ceil(Number(error.details?.retryAfterSeconds) || 1)) : undefined;
  return { status, code, message: error.message, details: error.details ?? {}, retryAfterSeconds };
}
